// Code generated by MockGen. DO NOT EDIT.
// Source: rustfmt.go
//
// Generated by this command:
//
//	mockgen -source=rustfmt.go -destination=rustfmt_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRustfmtChecker is a mock of RustfmtChecker interface.
type MockRustfmtChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRustfmtCheckerMockRecorder
	isgomock struct{}
}

// MockRustfmtCheckerMockRecorder is the mock recorder for MockRustfmtChecker.
type MockRustfmtCheckerMockRecorder struct {
	mock *MockRustfmtChecker
}

// NewMockRustfmtChecker creates a new mock instance.
func NewMockRustfmtChecker(ctrl *gomock.Controller) *MockRustfmtChecker {
	mock := &MockRustfmtChecker{ctrl: ctrl}
	mock.recorder = &MockRustfmtCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRustfmtChecker) EXPECT() *MockRustfmtCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRustfmtChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockRustfmtCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRustfmtChecker)(nil).Check), ctx, content)
}

// CheckWithOptions mocks base method.
func (m *MockRustfmtChecker) CheckWithOptions(ctx context.Context, content string, opts *RustfmtOptions) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithOptions", ctx, content, opts)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckWithOptions indicates an expected call of CheckWithOptions.
func (mr *MockRustfmtCheckerMockRecorder) CheckWithOptions(ctx, content, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithOptions", reflect.TypeOf((*MockRustfmtChecker)(nil).CheckWithOptions), ctx, content, opts)
}
